package com.arthpay.arthpay_java;

public class OrderPojo {
	private String orderInfo; //order Id generated by merchant. to identify this transaction
	private String currency; //currency for the transaction - currently INR:356
	private String amount; //amount in paise for eg: 5 rupees to be denoted as 500
	
	
	public String getOrderInfo() {
		return orderInfo;
	}
	public void setOrderInfo(String orderInfo) {
		this.orderInfo = orderInfo;
	}
	public String getCurrency() {
		return currency;
	}
	public void setCurrency(String currency) {
		this.currency = currency;
	}
	public String getAmount() {
		return amount;
	}
	public void setAmount(String amount) {
		this.amount = amount;
	}
	
}
